### ISSUE TITLE
USER STORY: Runner's feedback poll

### ISSUE THREAD

**Issue by mountaincharlie** [mountaincharlie/walkthrough-project#1]
As a **runner** I can **give feedback in a poll** so that **I can have a say in the best times and places for the runs**.

## Acceptance Criteria
* Acceptance Criteria 1: The runner can vote on the best times and the best places for runs
* Acceptance Criteria 2: The runner can add additional comments
* Acceptance Criteria 3: The runner can submit their feedback

## Tasks
- [ ] Design user poll interface for the 2 questions and adding comments
- [ ] Create poll interface with checkboxes for the questions and textarea for the comment
- [ ] Create submit button and thank you page when submitting the user's feedback
- [ ] Test poll functionality and the feedback once stored in the database
