### ISSUE TITLE
USER STORY: Poll results handling by site admin 

### ISSUE THREAD

**Issue by mountaincharlie** [mountaincharlie/walkthrough-project#2]
As a **site administrator** I can **add up and keep records of the poll results** so that **I can feedback to our running team on what the site's users want**.

## Acceptance Criteria
* Acceptance Criteria 1: The poll results for the week are added and can be accessed by the admin 
* Acceptance Criteria 2: The runner's comments can be accessed by the admin

## Tasks
- [ ] Design screen for the admin viewing the poll results and comments
- [ ] Create the screen for the admin viewing the poll results and comments
- [ ] Test the admin being able to access weekly data and publish for the running team
